CREATE DATABASE CONTROLSALUD;

USE CONTROLSALUD;

/* TABLA DE USUARIOS */
CREATE TABLE USUARIOS (
    USU_ID INT PRIMARY KEY AUTO_INCREMENT,
    USU_TIP_ID INT,
    USU_IDEN INT,
    USU_NOMBRES VARCHAR(100),
    USU_APELLIDOS VARCHAR(100),
    LOG_USER VARCHAR(50),
    LOG_PASS VARCHAR(50),
    USU_GENERO INT,
    USU_EMAIL VARCHAR(100),
    USU_TIPO INT
);

/* TABLA DE DOCTORES */
CREATE TABLE DOCTORES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PRIMERNOMBRE VARCHAR(50),
    SEGUNDONOMBRE VARCHAR(50),
    ID_ESPECIALIDAD INT
);

/* TABLA DE CITAS MÉDICAS */
CREATE TABLE CITASMEDICAS (
    IDCITA INT PRIMARY KEY AUTO_INCREMENT,
    FECHAHORA DATETIME,
    ESTADO VARCHAR(20),
    ID_CONSULTORIO INT
);

/* TABLA DE ESPECIALIDADES */
CREATE TABLE ESPECIALIDADES (
    IDESPECIALIDAD INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100)
);

/* TABLA DE CONSULTORIOS */
CREATE TABLE CONSULTORIOS (
    IDCONSULTORIO INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO INT,
    UBICACION VARCHAR(100),
    DISPONIBILIDAD VARCHAR(20)
);

/* TABLA DE PACIENTES */
CREATE TABLE PACIENTES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PACIENTE_TIP_ID INT,
    PACIENTE_IDEN INT,
    PRIMERNOMBRE VARCHAR(50),
    SEGUNDONOMBRE VARCHAR(50),
    ID_GENERO INT,
    FECHANACIMIENTO DATE,
    CORREO VARCHAR(100)
);

/* TABLA DE HISTORIALES MÉDICOS */
CREATE TABLE HISTORIALESMEDICOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ENFERMEDADESPREVIAS TEXT
);

CREATE TABLE PACIENTES_HISTORIALESMEDICOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_PACIENTE INT,
    ID_HISTORIALMEDICO INT
);

CREATE TABLE TIP_IDEN (
    TIP_IDEN_ID INT PRIMARY KEY AUTO_INCREMENT,
    TIP_ID_DESCRIPCION VARCHAR(20)
);

CREATE TABLE GENEROS (
    GEN_ID INT PRIMARY KEY AUTO_INCREMENT,
    GEN_DESCRIPCION VARCHAR(20)
);

CREATE TABLE TIPO_USU (
    ID_TIPO_USU INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_USU_DESCRIPCION VARCHAR(50)
);

ALTER TABLE USUARIOS ADD CONSTRAINT USUARIOS_TIP_IDEN
FOREIGN KEY (USU_TIP_ID) REFERENCES TIP_IDEN(TIP_IDEN_ID);

ALTER TABLE USUARIOS ADD CONSTRAINT USUARIOS_GENEROS
FOREIGN KEY (USU_GENERO) REFERENCES GENEROS(GEN_ID);

ALTER TABLE USUARIOS ADD CONSTRAINT USUARIOS_TIPO_USU
FOREIGN KEY (USU_TIPO) REFERENCES TIPO_USU(ID_TIPO_USU);

ALTER TABLE PACIENTES ADD CONSTRAINT PACIENTES_TIP_IDEN
FOREIGN KEY (PACIENTE_TIP_ID) REFERENCES TIP_IDEN(TIP_IDEN_ID);

ALTER TABLE PACIENTES ADD CONSTRAINT PACIENTES_GENEROS
FOREIGN KEY (ID_GENERO) REFERENCES GENEROS(GEN_ID);

ALTER TABLE PACIENTES_HISTORIALESMEDICOS ADD CONSTRAINT PACIENTES_PACIENTES_HISTORIALESMEDICOS
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID);

ALTER TABLE PACIENTES_HISTORIALESMEDICOS ADD CONSTRAINT HISTORIALESMEDICOS_PACIENTES_HISTORIALESMEDICOS
FOREIGN KEY (ID_HISTORIALMEDICO) REFERENCES HISTORIALESMEDICOS(ID);

ALTER TABLE DOCTORES ADD CONSTRAINT DOCTORES_ESPECIALIDADES
FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES ESPECIALIDADES(IDESPECIALIDAD);

ALTER TABLE CITASMEDICAS ADD CONSTRAINT CITASMEDICAS_CONSULTORIOS
FOREIGN KEY (ID_CONSULTORIO) REFERENCES CONSULTORIOS(IDCONSULTORIO);

INSERT INTO TIPO_USU (TIPO_USU_DESCRIPCION) VALUES('COTIZANTE');
INSERT INTO TIPO_USU (TIPO_USU_DESCRIPCION) VALUES('BENEFICIARIO');

INSERT INTO GENEROS (GEN_DESCRIPCION) VALUES('MASCULINO');
INSERT INTO GENEROS (GEN_DESCRIPCION) VALUES('FEMENINO');
INSERT INTO GENEROS (GEN_DESCRIPCION) VALUES('PREFIERO NO DECIRLO');

INSERT INTO TIP_IDEN (TIP_ID_DESCRIPCION) VALUES('CÉDULA DE CIUDADANÍA');
INSERT INTO TIP_IDEN (TIP_ID_DESCRIPCION) VALUES('TARJETA DE IDENTIDAD');
INSERT INTO TIP_IDEN (TIP_ID_DESCRIPCION) VALUES('PASAPORTE');
INSERT INTO TIP_IDEN (TIP_ID_DESCRIPCION) VALUES('NIT');

INSERT INTO HISTORIALESMEDICOS (ENFERMEDADESPREVIAS) VALUES('N/A');
INSERT INTO HISTORIALESMEDICOS (ENFERMEDADESPREVIAS) VALUES('ANGINA DE PECHO');
INSERT INTO HISTORIALESMEDICOS (ENFERMEDADESPREVIAS) VALUES('ASMA');
INSERT INTO HISTORIALESMEDICOS (ENFERMEDADESPREVIAS) VALUES('HIPERTENSIÓN');
INSERT INTO HISTORIALESMEDICOS (ENFERMEDADESPREVIAS) VALUES('DIABETES');
INSERT INTO HISTORIALESMEDICOS (ENFERMEDADESPREVIAS) VALUES('OBESIDAD');
INSERT INTO HISTORIALESMEDICOS (ENFERMEDADESPREVIAS) VALUES('CANCER');
INSERT INTO HISTORIALESMEDICOS (ENFERMEDADESPREVIAS) VALUES('ESTRES');
INSERT INTO HISTORIALESMEDICOS (ENFERMEDADESPREVIAS) VALUES('INFLUENZA');
INSERT INTO HISTORIALESMEDICOS (ENFERMEDADESPREVIAS) VALUES('COVID-19');
INSERT INTO HISTORIALESMEDICOS (ENFERMEDADESPREVIAS) VALUES('VIH');
INSERT INTO HISTORIALESMEDICOS (ENFERMEDADESPREVIAS) VALUES('H1N1');

INSERT INTO CONSULTORIOS (NUMERO, UBICACION, DISPONIBILIDAD) VALUES(101, 'CARRERA 14 #96-22', 'DISPONIBLE');
INSERT INTO CONSULTORIOS (NUMERO, UBICACION, DISPONIBILIDAD) VALUES(102, 'CARRERA 14 #96-22', 'DISPONIBLE');
INSERT INTO CONSULTORIOS (NUMERO, UBICACION, DISPONIBILIDAD) VALUES(103, 'CARRERA 14 #96-22', 'DISPONIBLE');
INSERT INTO CONSULTORIOS (NUMERO, UBICACION, DISPONIBILIDAD) VALUES(201, 'CARRERA 14 #96-22', 'DISPONIBLE');
INSERT INTO CONSULTORIOS (NUMERO, UBICACION, DISPONIBILIDAD) VALUES(202, 'CARRERA 14 #96-22', 'DISPONIBLE');
INSERT INTO CONSULTORIOS (NUMERO, UBICACION, DISPONIBILIDAD) VALUES(301, 'CARRERA 14 #96-22', 'DISPONIBLE');
INSERT INTO CONSULTORIOS (NUMERO, UBICACION, DISPONIBILIDAD) VALUES(401, 'CARRERA 14 #96-22', 'NO DISPONIBLE');

INSERT INTO ESPECIALIDADES (NOMBRE) VALUES('MEDICINA GENERAL');
INSERT INTO ESPECIALIDADES (NOMBRE) VALUES('OPTOMETRÍA');
INSERT INTO ESPECIALIDADES (NOMBRE) VALUES('PSICOLOGÍA');
INSERT INTO ESPECIALIDADES (NOMBRE) VALUES('PEDIATRÍA');
INSERT INTO ESPECIALIDADES (NOMBRE) VALUES('ONCOLOGÍA');

INSERT INTO CITASMEDICAS (FECHAHORA, ESTADO, ID_CONSULTORIO) VALUES('2024-05-30 12:35:00', 'ACTIVA', 3);

INSERT INTO DOCTORES (PRIMERNOMBRE, SEGUNDONOMBRE, ID_ESPECIALIDAD) VALUES('ORLANDO', 'PÉREZ', 2);

INSERT INTO PACIENTES (PACIENTE_TIP_ID, PACIENTE_IDEN, PRIMERNOMBRE, SEGUNDONOMBRE, ID_GENERO, FECHANACIMIENTO, CORREO) 
VALUES (1, 11230262, 'DIEGO ALEJANDRO', 'LOPÉZ MARTÍNEZ', 1, '1998-07-24', 'diegoalej@gmail.com');

INSERT INTO PACIENTES_HISTORIALESMEDICOS (ID_PACIENTE, ID_HISTORIALMEDICO) VALUES(1, 3);
INSERT INTO PACIENTES_HISTORIALESMEDICOS (ID_PACIENTE, ID_HISTORIALMEDICO) VALUES(1, 8);

INSERT INTO USUARIOS (USU_TIP_ID, USU_IDEN, USU_NOMBRES, USU_APELLIDOS, LOG_USER, LOG_PASS, USU_GENERO, USU_EMAIL, USU_TIPO)
VALUES(1, 1000474272, 'ANDRÉS ESTIVEN', 'GARCÍA PÁEZ', 'andres', 'andres123', 1, 'aestgarcia@poligran.edu.co', 1);